language: node_js
node_js:
    - node
cache:
    directories:
        - node_modules
before_install:
    - npm i -g npm@latest
install:
    - npm ci
before_script:
    - npm run lint
script:
    - npm run build
deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: false
    local-dir: dist
